title: SUPERDYLANYT
description: Bienvenido
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
social:
  twitter: DYLAN1456711
  github: dylan14567
  youtube: UCXZow-eof6WFmu4armVahAA
plugins:
 - jekyll-feed
 - jekyll-seo-tag
