title: Dylan Meca
description: Soy Dylan Meca, científico e ingeniero en informática.
author:
  name: Dylan Meca
  email: 
show_downloads: false
google_analytics: G-588R86TJDG
comments: true
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: DYLAN1456711
    github: dylan14567
    youtube_channel: UCSUN3qthUfkVO2OwnJh3HQg
    instagram: dylan14567.oficial

theme: minima

disqus:
  shortname: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
